<a href="https://colab.research.google.com/github/Bund798/Decision_Tree/blob/master/decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [58]:
dataset=pd.read_csv("/content/balance-scale.csv")
dataset.head()

Class_Name  Left-Weight  Left-Distance  Right-Weight  Right-Distance
0          R            1              1             3               5
1          R            1              1             4               1
2          R            1              1             4               2
3          R            1              1             4               3
4          R            1              1             4               4

In [59]:
from sklearn.preprocessing import LabelEncoder
le_class_name=LabelEncoder()
dataset['class_name']=le_class_name.fit_transform(dataset['Class_Name'])
dataset.head()

Class_Name  Left-Weight  ...  Right-Distance  class_name
0          R            1  ...               5           2
1          R            1  ...               1           2
2          R            1  ...               2           2
3          R            1  ...               3           2
4          R            1  ...               4           2

[5 rows x 6 columns]

In [60]:
dataset=dataset.drop('Class_Name',axis=1)
dataset.head()

Left-Weight  Left-Distance  Right-Weight  Right-Distance  class_name
0            1              1             3               5           2
1            1              1             4               1           2
2            1              1             4               2           2
3            1              1             4               3           2
4            1              1             4               4           2

In [61]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(dataset.drop('class_name',axis=1),dataset.class_name,test_size=0.3)


In [62]:
from sklearn import tree
model=tree.DecisionTreeClassifier(criterion='entropy',splitter='random')
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='random')

In [63]:
y_pred=model.predict(X_test)

In [64]:
print('Accuracy:',metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.782608695652174


In [65]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 0  4  9]
 [ 9 86  3]
 [11  4 58]]
